# fly.toml app configuration file generated for silent-hill-4231 on 2023-11-01T10:44:01+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "silent-hill-4231"
primary_region = "lhr"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.20.2"

[[services]]
  internal_port = 8080
  processes = ["app"]
 
 

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]
    
  [[services.script_checks]]
    command       = "/app/health_check.sh"
    grace_period  = "2s"
    interval      = "5s"
    restart_limit = 0
    timeout       = "1s"
