# fly.toml app configuration file generated for wispy-bird-6249 on 2023-11-03T04:38:32+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wispy-bird-6249"
primary_region = "lhr"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.20.2"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  
  [[services.script_checks]]
    command       = "/app/health_check.sh"
    grace_period  = "2s"
    interval      = "5s"
    restart_limit = 0
    timeout       = "1s"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]


