name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies 
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: e2e tests
        uses: cypress-io/github-action@v6
        with:                 
          build: npm run build
          start: npm run start-prod
          command: npm run test:e2e
          wait-on: http://localhost:5000      

      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: "Commit ${{ github.event.head_commit.url || github.event.pull_request.commits_url }} by ${{ github.actor }} broke the build :("
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}   
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      
            
      - name: Deploy to production
        if: ${{ contains(fromJSON('["push"]'), github.event_name) && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }} 
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        if: ${{ contains(fromJSON('["push"]'), github.event_name) && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: New version of Pokedex deploeyd successfully
        if: success()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          description: to https://deploy-test-15l8.onrender.com/ by ${{ github.event.pusher.name }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}  

      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: "Commit ${{ github.event.head_commit.url || github.event.pull_request.commits_url }} by ${{ github.actor }} broke the build :("
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}    
