name: My Deploy
# some comment ...
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master]
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        if: ${{ github.event_name == 'push' }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}        
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          
